# .terraform-docs.yml

formatter: "markdown table"
settings:
  color: true
content: |-
  {{ .Header }}
  
  {{ .Requirements }}

    ## Simple module usage
        
    ```hcl
    {{ include "examples/example-1/main.tf" }}
    ```
    ### See more usage examples here:
    - [:arrow_forward: Example: Creating a Subnet with Network Security Group and Route Table in Azure](examples/example-2/main.tf)
    - [:arrow_forward: Example: Creating Subnet, NSG, Route Table, and Adding UDR for NVA](examples/example-3/main.tf)
    - [:arrow_forward: Example: Creating a Subnet with Network Security Group, Route Table, and Service Endpoints](examples/example-4/main.tf)
    - [:arrow_forward: Example: Creating Subnet, NSG, and Route Table in an Existing Resource Group](examples/example-5/main.tf)

    > :information_source: **Note:** <br>
    > Otherwise, see the full module test here: [:arrow_forward: test/autotest](test/autotest/main.tf) <br>

  {{ .Resources }}
  {{ .Inputs }}
  {{ .Outputs }}
  {{ .Modules }}
  {{ .Footer }}

recursive:
  enabled: false

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  required: true
  sensitive: true
  type: true
