### This Workflow fully automates a Git release after a Pull Request that is not created by depandabot is merged.

name: "Automated Release"
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  if_merged:
    name: Bump, Tag and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    if: ${{ (github.event.pull_request.merged) && (github.actor != 'dependabot[bot]') }}
    steps:
      - uses: actions/checkout@v4
      - uses: jefflinse/pr-semver-bump@v1.6.0
        id: bump-tag-version
        name: Bump and Tag Version
        with:
          mode: bump
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          require-release-notes: true
          noop-labels: "no release"
          major-label: "major"
          minor-label: "minor"
          patch-label: "patch"
          base-branch: "main"

      # - name: Getting version from label
      #   id: label
      #   uses: zwaldowski/match-label-action@v5
      #   with:
      #     allowed: major, minor, patch
      #     default_match: patch
      
      # - name: Determine version
      #   id: version
      #   uses: zwaldowski/semver-release-action@v4
      #   with:
      #     bump: patch
      #     dry_run: true
      #     github_token: ${{secrets.GITHUB_TOKEN}}

        if: ${{ steps.bump-tag-version.outputs.skipped == 'false' }}
      - name: Create new release and push to registry
        id: release
        uses: ncipollo/release-action@v1.14.0
        with:
          generateReleaseNotes: true
          name: "v${{ steps.bump-tag-version.outputs.version}}"
          tag: "${{ steps.bump-tag-version.outputs.version }}"
          # name: "v${{ steps.version.outputs.version }}"
          # tag: ${{ steps.version.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
