### This Workflow fully automates a Git release after a Pull Request that is not created by depandabot is merged.

name: "Automated Release"
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  get_version_label:
    name: Get Version from label
    if: ${{ (github.event.pull_request.merged) && (github.actor != 'dependabot[bot]') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
      - name: Getting version from label
        id: label
        uses: zwaldowski/match-label-action@v5
        with:
          allowed: major, minor, patch
          default_match: "no release"

      - name: Determine version
        if: ${{ steps.label.outputs.match != 'no release' }}
        id: version
        uses: zwaldowski/semver-release-action@v4
        with:
          bump: ${{ steps.label.outputs.match }}
          dry_run: true
          github_token: ${{secrets.GITHUB_TOKEN}}

      - name: Create new release and push to registry
        if: ${{ steps.label.outputs.match != 'no release' }}
        id: release
        uses: ncipollo/release-action@v1.14.0
        with:
          generateReleaseNotes: true
          name: "v${{ steps.version.outputs.version }}"
          tag: ${{ steps.version.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}